import { test, expect } from "@playwright/test";

test.describe(
  "Make Appointment",
  {
    annotation: {
      type: "Story",
      description: "JIRA-1234:Make Appointment Test",
    },
    tag: "@Regression",
  },
  () => {
    test.beforeEach(
      "Login with valid credentials",
      async ({ page }, TestInfo) => {
        await page.goto("https://katalon-demo-cura.herokuapp.com/");
        await expect(page).toHaveTitle("CURA Healthcare Service");
        await expect(page.locator("//h1")).toHaveText(
          "CURA Healthcare Service",
        );

        //Click On Make an Appointment
        await page.getByRole("link", { name: "Make Appointment" }).click();

        //Add Screenshot for the login page
        let loginPageFullscreenshot = await page.screenshot({
          fullPage: true,
        });
        await TestInfo.attach("Login Page Screenshot", {
          body: loginPageFullscreenshot,
          contentType: "image/png",
        });

        //Success Login
        await page.getByLabel("Username").click();
        await page.getByLabel("Username").fill("John Doe");
        await page.getByLabel("Password").click();
        await page.getByLabel("Password").fill("ThisIsNotAPassword");
        await page.getByRole("button", { name: "Login" }).click();

        //Assert a text
        await expect(page.locator("h2")).toContainText("Make Appointment");
      },
    );

    test(
      "Should make an appointment with non deafult values",
      {
        annotation: {
          type: "Bug",
          description: "Bug-1234: Not working in Webkit",
        },
        tag: "@smoke",
      },
      async ({ page }) => {
        //Drop down box selection
        await page
          .getByLabel("Facility")
          .selectOption("Hongkong CURA Healthcare Center");

        //Check box selection
        await page
          .getByRole("checkbox", { name: "Apply for hospital readmission" })
          .check();

        //Radio button selection
        await page.getByRole("radio", { name: "Medicaid" }).check();

        //Date Field selection
        await page.locator("#txt_visit_date").click();
        const day = page.locator(
          ".datepicker-days td.day:not(.old):not(.new)",
          {
            hasText: "2",
          },
        );
        await day.first().click();

        //Multi-line text box
        await page.getByRole("textbox", { name: "Comment" }).click();
        await page
          .getByRole("textbox", { name: "Comment" })
          .fill(
            "This is a multline appointment generated by the Playwright codegen feature",
          );

        //Button click
        await page.getByRole("button", { name: "Book Appointment" }).click();

        //Assertions
        await expect(
          page.getByRole("link", { name: "Go to Homepage" }),
        ).toBeVisible();
        await expect(page.locator("h2")).toContainText(
          "Appointment Confirmation",
        );
      },
    );
  },
);
